### ISSUE TITLE
No time and/or energy to maintain this project

### ISSUE THREAD

**Issue by robinwassen** [synhershko/NAppUpdate#106]
Hi @synhershko,

I would just like to say that I will not have the time and energy to maintain this project forward from now -, it was appreciated that I got contributor access to push it forward and work on the stability and maintainability of it.

I will complete the review and merge of #99 though since I started that work, if you still want to keep me with contributor access that is fine.

So I would recommend that you bring in additional contributors to this project, one candidate is @vbjay that has contributed a lot of work to it.

The only thing that I need to hand over to someone else is the Nuget package ownership.

Regards,
Robin Andersson

**Comment by synhershko** [comment]
Thank you @robinwassen for all your hard work on this project so far. This is an evolution of an OSS project  - I, too, was using this library and maintaining it until I wasn't :)

You can hand the nuget ownership over to me.

Anyone else willing to get contributor access - just let me know.

Thanks so much again!

**Comment by robinwassen** [comment]
@synhershko Thanks :)

What is your username on Nuget?

**Comment by synhershko** [comment]
Same as here

--

Itamar Syn-Hershko
Freelance Developer & Consultant
Elasticsearch Partner
Microsoft MVP | Lucene.NET PMC
http://code972.com | @synhershko <https://twitter.com/synhershko>
http://BigDataBoutique.co.il/
