### ISSUE TITLE
Provide builds for framework versions > 2.0

### ISSUE THREAD

**Issue by synhershko** [synhershko/NAppUpdate#27]
To allow for dynamically loading assemblies during cold-updates

Otherwise, this exception is thrown

   System.BadImageFormatException: This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded. (Exception from HRESULT: 0x8013101B)

**Comment by robinwassen** [comment]
This has been done in: https://github.com/synhershko/NAppUpdate/pull/85
