### ISSUE TITLE
UnauthorizedAccessException updating file

### ISSUE THREAD

**Issue by tverona** [synhershko/NAppUpdate#35]
Hi, I hit the following error:
Debug	Creating Temp directory C:\Users\Tomer\AppData\Local\Temp\149a22f3-9195-4577-aab9-43f79a89c9d0 
Debug	FileUpdateTask: Downloading foo.exe with BaseUrl of http://localhost:8888 to C:\Users\Tomer\AppData\Local\Temp\149a22f3-9195-
Debug	FileUpdateTask: Prepared successfully; destination file: C:\Users\Tomer\bar\foo.exe 
Debug	Starting to process cold updates... 
Debug	Update process name: 'NAppUpdateProcess' 
Debug	Loading C:\Users\Tomer\AppData\Local\Temp\149a22f3-9195-4577-aab9-43f79a89c9d0\foo.exe 
Debug		Skipping (part of current execution) 
Debug	Loading C:\Users\Tomer\AppData\Local\Temp\149a22f3-9195-4577-aab9-43f79a89c9d0\NAppUpdate.Framework.dll 
Debug		Skipping (part of current execution) 
Debug	The application has terminated (as expected) 
Debug	Got 1 task objects 
Debug	Task "": RequiresAppRestart 
Debug		Executing... 
Error	
Could not replace the file
System.UnauthorizedAccessException: Access to the path 'C:\Users\Tomer\bar\foo.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.Delete(String path)
   at NAppUpdate.Framework.Tasks.FileUpdateTask.Execute(Boolean coldRun) 
Debug		Task execution failed 
Error	Update failed 
Debug	Re-launching process C:\Users\Tomer\bar\foo.exe with working dir C:\Users\Tomer\bar 

I am using the latest sources from github.

Thanks,
Tomer

**Comment by robinwassen** [comment]
The problem seems to be when updater is faster to try to replace files than the OS is to release locks on the files after the mutex has been released.

I have proposed a fix in #86

**Comment by robinwassen** [comment]
This fix has been merged and will be released in 0.5.1.0

**Comment by synhershko** [comment]
Awesome, looks great! Thanks!
