### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by Svish** [synhershko/NAppUpdate#37]
Could you perhaps make a [Nuget package](http://nuget.org/packages?q=NAppUpdate) for this library? Would make things a lot smoother :)

**Comment by robinwassen** [comment]
I managed to steal the name NAppUpdate.Framework on NuGet for my fork of the framework, but we started to work on bringing this repo up to speed with mine and centralizing all the work to this repo.

As soon as I feel that this repo is up to speed with my repo the NuGet package will be published at: https://www.nuget.org/packages/NAppUpdate.Framework

Currently it is my fork that is published there.

**Comment by robinwassen** [comment]
Everything is setup for publishing a nuget package now, will do it as soon as we hit the 0.4.0.0 milestone.

**Comment by robinwassen** [comment]
A nuget has now been published: https://www.nuget.org/packages/NAppUpdate.Framework/0.4.0
