### ISSUE TITLE
App requires admin permission after update

### ISSUE THREAD

**Issue by UXDart** [synhershko/NAppUpdate#43]
Hi. I have a working project. the only problem is this:
- the app is installed with an installer, it works for admins and non admins.
- the self-update works ok (I run the app as admin) it restarts and it is updated
- the problem is that now the main .exe has permissions only for the admin user and admins. so when I log in as a non-admin user, it doesn't work anymore.

any idea how can I fix this?

TIA

**Comment by vbjay** [comment]
The way around this is to check if the current user has write access to the files. If not, make the updater run elevated.

**Comment by ianwall** [comment]
This one causes me a lot of problems. I'm happy to do a PR to add this to FileUpdateTask.cs:

    // Copy _detinationFile access rights to _tempFile before Move.
    FileInfo fiDest = new FileInfo(_destinationFile);
    FileInfo fiSrc = new FileInfo(_tempFile);
    FileSecurity ac = fiDest.GetAccessControl();
    ac.SetAccessRuleProtection(true, true);
    fiSrc.SetAccessControl(ac);

?

**Comment by robinwassen** [comment]
@ianwall What problem does that code solve?

**Comment by ianwall** [comment]
The one this thread is about - i.e. after an update the file permissions are changed to include s specific user, rather than 'users', so the next update fails. This copies the original files permissions, rather than adding 'Users' to the files as per @jderoij's quickfix.

**Comment by robinwassen** [comment]
@ianwall Sounds like a proper solution. A PR would be appriciated.

**Comment by robinwassen** [comment]
This has been resolved thanks to @ianwall and will be included in the next release.
