### ISSUE TITLE
"Current Version" doesn't update in WPF sample

### ISSUE THREAD

**Issue by CoderNate** [synhershko/NAppUpdate#49]
I think the first thing a lot of people would do to try out this project is run the WPF sample app.  When doing so it's likely they'll notice that the Current Version displayed on the main window usually doesn't change from 1.0 to 1.1 as expected after doing an "Install Now".  In the following code from UpdateWindow.xaml.cs you can see it's possible for updateManager.CleanUp to finish before the BeginInvoke that closes the update window finishes.  If that happens, the CleanUp method sets the updatemanager's state back to unchecked _before_ the closed event handler inside the main window does its check to see that the state is AppliedSuccessfully.  The Closed handler in the MainWindow code only calls OnPropertyChanged("AppVersion") if the state is AppliedSuccessfully.  Maybe the easiest thing is to make sure the Update window closes before CleanUp is called.

```
private void InstallNow_Click(object sender, RoutedEventArgs e)
{
...
    Dispatcher d = Application.Current.Dispatcher;
    d.BeginInvoke(new Action(Hide));
    try
    {
        _updateManager.ApplyUpdates(true);
        d.BeginInvoke(new Action(Close));
    }
    catch
    {
        d.BeginInvoke(new Action(this.Show));
            // this.WindowState = WindowState.Normal;
        MessageBox.Show(
            "An error occurred while trying to install software updates");
    }

    _updateManager.CleanUp();
    d.BeginInvoke(new Action(this.Close));

    Action close = Close;

    if (Dispatcher.CheckAccess())
        close();
    else
        Dispatcher.Invoke(close);
...
}
```

**Comment by robinwassen** [comment]
This has been fixed in commit: 6fc8c6f984769bd841e3bbfe0b7b04f7a27208fb

Thanks for reporting this issue.
