### ISSUE TITLE
Failed to get correct version info on some DLLs. 

### ISSUE THREAD

**Issue by galendai** [synhershko/NAppUpdate#51]
Just running into an odd issue when trying to update a DLL from CefSharp3, **libEGL.dll**. Under *FileVersionCondition.cs* line 40: ```versionString = versionInfo.FileVersion``` will return product version which is **2.1.f4126d2b9eb0**. This will cause *Incorrect string format* exception when we try to create new localVersion instance in the next line by simply pass this string into ```var localVersion = new Version(versionString)```.

Not sure if this is just an odd issue, it might be safer to use ```new Version (int major, int minor, int build, int revision)``` in both FileVersionCondition.cs and FeedBuilder to get the correct file version to avoid exception. 

Just my 2 cents and thanks for the awesome work. Cheers! :+1:

**Comment by synhershko** [comment]
Thanks - will appreciate a PR to fix this :)

**Comment by synhershko** [comment]
Fixed by #52
