### ISSUE TITLE
CheckForUpdates() showing as another process is already running

### ISSUE THREAD

**Issue by SSiCincinnati** [synhershko/NAppUpdate#53]
When I check for updates, using "UpdateManager.Instance.CheckForUpdates()", I get the InvalidOperationException "Another update process is already in progress", although nothing else is running this update.  What could be causing this to get marked as in progress?

**Comment by synhershko** [comment]
Can you provide a repro showing this?

**Comment by SSiCincinnati** [comment]
Well, I added a direct call to UpdateManager.Instance.CleanUp() after checking for updates and either applying updates or letting the user know that there were no updates, and this issue has been resolved.
However, I'm now encountering an issue only with the release version of my code.  When I check for updates, I get a message saying "Version string portion with too short or too long".  Is there a set length that the versions have to be?  When I use the FeedBuilder.exe program, I do not get any errors about the version numbers.

**Comment by SSiCincinnati** [comment]
Also, when I am debugging my program, the check for updates work correctly.

**Comment by robinwassen** [comment]
**Regarding the version problem:**

NAppUpdate uses the System.Version constuctor Version(String), so I guess you get ArgumentException from it when it tries to check if the version is met. You can see what is wrong with your version by reading the ArgumentException description here: https://msdn.microsoft.com/en-us/library/y0hf9t2e(v=vs.110).aspx

One could argue that the FeedBuilder should check this when creating the xml.

**Regarding the Updater already running problem:**

We will need more information regarding this one if we are to look into this, I would guess there either is two calls to some NAppUpdate function or you are not calling them in the correct order. Some more information on what methods you try to call and in what order you do it would be helpful.

Closing until more information is added.
