### ISSUE TITLE
Move samples to orphan branch?

### ISSUE THREAD

**Issue by robinwassen** [synhershko/NAppUpdate#59]
I normally prefer to move the samples to a separate branch, this to keep the main branch as clean as possible.

Did it on my fork of the project: https://github.com/robinwassen/NAppUpdate2

@synhershko What are your thoughts on this?

**Comment by synhershko** [comment]
I think it's less obvious to people, especially newbies to NAU or git in general. Let's keep samples on master, under their own folder. It's as clean as it gets IMO.

**Comment by robinwassen** [comment]
OK!
