### ISSUE TITLE
Make indentation consistent in the whole project

### ISSUE THREAD

**Issue by robinwassen** [synhershko/NAppUpdate#60]
The current indentation is currently mixed between tabs and spaces, which sometimes makes a mess when people send pull requests.

@synhershko Should we settle for tabs as indentation for the whole project? I can do the dirty work of converting all indentation.

**Comment by synhershko** [comment]
Sure. We can use http://editorconfig.org/ to enforce, I prefer it to StyleCop

**Comment by robinwassen** [comment]
Great!

I will convert the project and write some basic guidelines. The main thing that I want to avoid is PR:s that should be about 3 lines modified but end up being 500 lines due to some indentation change.
