### ISSUE TITLE
Removal of stale branches?

### ISSUE THREAD

**Issue by robinwassen** [synhershko/NAppUpdate#68]
We currently have two stale branches:
- better-tasks, last modified: 2011
- web-deployment, last modified: 2011

I do not know the state of them and I suspect that it would be tremendous amount of work to merge them into master since they are so far behind.

@synhershko Should we remove them?

**Comment by synhershko** [comment]
IIRC better-tasks has some good ideas. web-deployment we can remove.

**Comment by robinwassen** [comment]
OK :+1:
