### ISSUE TITLE
Help with conditions

### ISSUE THREAD

**Issue by duard** [synhershko/NAppUpdate#80]
Please, how can I create an condition to update just newer files. It aways download/update ALL MY FILES on my XML 

`    <FileUpdateTask hotswap="true" updateTo="file://192.168.1.13/Build/AppSplash.dll" localPath="AppSplash.dll">
      <Description>UPDATE-7</Description>
      <Conditions>
        <FileDateCondition type="not" what="older" timestamp="09/20/2011 00:00:00 -4:00"/>
      </Conditions>
    </FileUpdateTask>
    <FileUpdateTask updateTo="file://192.168.1.13/Build/AppUpdate.dll" localPath="AppUpdate.dll" lastModified="131051666731851911">
      <Description>UPDATE-8</Description>
    </FileUpdateTask>
    <FileUpdateTask  hotswap="true" updateTo="file://192.168.1.13/Build/Leiame.txt" localPath="Leiame.txt" lastModified="131051666731851911">
      <Description>UPDATE-LEIAME</Description>
      <Conditions>
        <FileDateCondition what="newer" timestamp="09/20/2011 00:00:00 -4:00"/>
      </Conditions>
    </FileUpdateTask>
    <FileUpdateTask  hotswap="true" updateTo="file://192.168.1.13/Build/SimplesEmpresa.txt" localPath="SimplesEmpresa.txt" lastModified="131051666731851911">
      <Description>UPDATE-SIMPLESEMPRESA</Description>
      <Conditions>
        <FileDateCondition type="and" what="newer" timestamp="09/20/2011 00:00:00 -4:00"/>
      </Conditions>
    </FileUpdateTask>`

**Comment by synhershko** [comment]
Please use the mailing list to ask questions
