### ISSUE TITLE
upgrade framework 4

### ISSUE THREAD

**Issue by bbday** [synhershko/NAppUpdate#81]
It is possible upgrade version that not require framework 2 / 3.5
cause some user don't have access to windows feature to enable them.

Last framework it is 4.6 it thing it is a good thing have framework 4 for prerequisite and not old framework.

**Comment by synhershko** [comment]
Requiring the latest .NET framework will make that version of the framework a prerequisite, so using the latest is probably not a good idea. But I agree .NET 2 is too old at this point.

Closing as a duplicate of #27

**Comment by bbday** [comment]
Consider also with windows 10, framework 2 / 3.5 it is not installed, cause it have only framework 4 installed.

**Comment by robinwassen** [comment]
This issue will be solved by: https://github.com/synhershko/NAppUpdate/pull/85

Because that PR will include builds for both .Net 3.5 and .Net 4.0 in the nuget releases.
