### ISSUE TITLE
UpdateManager.Instance.BaseUrl is not accessible

### ISSUE THREAD

**Issue by suren1525** [synhershko/NAppUpdate#98]
I want to write my own UpdateTask 
MyUpdateTask : UpdateTaskBase

In my UpdateTask I need access to UpdateManager.Instance.BaseUrl as it is done in FileUpdateTask
string baseUrl = UpdateManager.Instance.BaseUrl;
but BaseUrl is internal :(
Could you make it public?
Thanks

**Comment by synhershko** [comment]
If you want to submit a PR we will gladly accept it
